# Generated by Django 3.2.16 on 2022-12-05 18:56

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cell', models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator('^7\\d{10}$', message='Телефонный номер не в формате 7XXXXXXXXXX')], verbose_name='Номер телефона')),
                ('code', models.CharField(max_length=3, validators=[django.core.validators.RegexValidator('^\\d{3}$', message='Код не из трёх цифр')], verbose_name='Код телефона')),
                ('tag', models.CharField(db_index=True, max_length=200, verbose_name='Тэг')),
                ('time_zone', models.CharField(default='UTC', max_length=200, verbose_name='Часовой пояс')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
            },
        ),
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(db_index=True, verbose_name='Дата и время начала рассылки')),
                ('end_time', models.DateTimeField(db_index=True, verbose_name='Дата и время конца рассылки')),
                ('text', models.CharField(max_length=200, verbose_name='Текст сообщения')),
                ('mailing_filters', models.JSONField(verbose_name='Фильтр свойств клиента')),
            ],
            options={
                'verbose_name': 'Mailing',
                'verbose_name_plural': 'Mailings',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Время создания')),
                ('send_status', models.CharField(choices=[('sent', 'Sent'), ('no sent', 'No sent')], max_length=7, verbose_name='Статус отправки')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client', to='api.client', verbose_name='Клиент')),
                ('mailing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message', to='api.mailing', verbose_name='Рассылка')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
            },
        ),
    ]
