# Generated by Django 3.2.16 on 2022-12-11 15:34

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='mailing_filters',
            field=models.JSONField(validators=[api.models.validate_mailing_filters], verbose_name='Фильтр свойств клиента'),
        ),
    ]
